# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: cmake --preset windows-ninja-msvc

    - name: Build
      run: cmake --build --preset windows-ninja-msvc-release

    - name: Package with CPack
      run: |
        cd build/windows-ninja-msvc
        cpack -C Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Typeit-windows-x64
        path: build/windows-ninja-msvc/*.zip

  ubuntu-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake --preset linux-base

    - name: Build
      run: cmake --build --preset linux-build

    - name: Package with CPack
      run: |
        cd build/linux-base
        cpack -C Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Typeit-linux-x64
        path: build/linux-base/*.zip

